name: Rudrakrit Backend Deployment

on: [push, workflow_dispatch]

jobs:
deploy:
runs-on: self-hosted
steps:
- name: Checkout code
uses: actions/checkout@v4

```
  - name: Test runner
    run: echo "GitHub Actions runner is working"
```
